Fix development version tests on qsolver-r branch
The existing CI failure looks like:

```
py: commands_pre[1]> maturin develop --release --manifest-path rust_ext/Cargo.toml
🍹 Building a mixed python/rust project
🔗 Found pyo3 bindings with abi3 support
🐍 Not using a specific python interpreter
📡 Using build options profile, features, bindings from pyproject.toml
Processing /qiskit/dist/qiskit-2.2.0-cp39-abi3-linux_x86_64.whl
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: '/qiskit/dist/qiskit-2.2.0-cp39-abi3-linux_x86_64.whl'
```

It seems that maturin is unable to handle the relative path(s),
so this commit use absolute paths instead.