Enhanced qubit solver (#222)
* First draft

* Add notebook guide

* style

* Ignore rust modules in Sphinx

* cleanup

* Private int conversion func

* Unit tests and style check passing.

* Fix env issues with tox

* Don't test against py39 in min version tests

* use quotes for py version in Actions

* Dont test against py39 in latest version testing

* Remove functions from api docs

* Add the abipy310 as pyo3 feature during build

* Move rust machinery inside the package

* Use py310 for all workflows

* debugging ci

* everything passing locally

* duplicate cell in notebook

* Co-authored-by: Javier Robledo Moreno <j.robledomoreno@ibm.com>

* fix lint

* Install rust toolchain in Actions

* fix rust setup

* help Actions find the manifest

* build rust extension and install maturin in workflow

* Install wheel manually, avoid making venv for maturin

* fix path to wheel

* Give package a valid name

* Refactor rust ext setup, install rust in Action, install package and rust ext within tox

* Restore more py versions to latest workflow

* Make changes to other workflows for installing rust

* Move to current rust Action

* Fix action

* Update workflows to use supported Action

* Try abi3-py39

* Try abi3-py39

* Fix bindings in pyproject

* py310 minimum

* dont implicitly cast np uint64 to python ints

* bumpy numpy version to support shifting np ints by python ints

* Fix development version tests on qsolver-r branch

The existing CI failure looks like:

```
py: commands_pre[1]> maturin develop --release --manifest-path rust_ext/Cargo.toml
🍹 Building a mixed python/rust project
🔗 Found pyo3 bindings with abi3 support
🐍 Not using a specific python interpreter
📡 Using build options profile, features, bindings from pyproject.toml
Processing /qiskit/dist/qiskit-2.2.0-cp39-abi3-linux_x86_64.whl
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: '/qiskit/dist/qiskit-2.2.0-cp39-abi3-linux_x86_64.whl'
```

It seems that maturin is unable to handle the relative path(s),
so this commit use absolute paths instead.

* Use real paths in dev version tests

* Dont allow Cargo lock files in commits

* Remove reference to deleted nb from tox

* Dont use setuptools

* Add note about rust toolchain

* Remove old note

* Fix varname

* Remove rust_ext dir

* Remove rust_ext from Actions

* style

* tidy up

* Clean up verbose

* linter

* Don't use verbose

* release notes

* strings around py versions

* cleanup

* rust documentation

* Fix description of function

* Speed up generate sp elems

* test something

* build rust extension in new test env

---------

Co-authored-by: Jim Garrison <garrison@ibm.com>